### ISSUE TITLE
Issue on getAbsolutePath() on windows

### ISSUE THREAD

**Issue by ptimatth** [Yuyz0112/icomoon-cli#15]
process.env.PWD is undefined on widowns, same isue a this project:
https://github.com/mrblueblue/gettext-loader/issues/18#issue-209744146

Can you fix to use process.cwd() if PWD is undefined ?

**Comment by ptimatth** [comment]
Stack trace: on windows:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at getAbsolutePath (C:\Your\Working\Dir\node_modules\icomoon-cli\index.js:54:34)
    at pipeline (C:\Your\Working\Dir\\node_modules\icomoon-cli\index.js:117:43)
    at Object.<anonymous> (C:\Your\Working\Dir\node_modules\icomoon-cli\gen-icomoon.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Yuyz0112** [comment]
Hi @ptimatth , I may need to find some time to do this fix. Would you like to send a PR?

**Comment by ptimatth** [comment]
Hi @Yuyz0112, job done, i have add a fix from @omarbenn fork due to heavy set of icons.

Can you add a reference of your account on npmjs.com to access easyly to your repo.

**Comment by Yuyz0112** [comment]
@ptimatth I have released the new version with git url
